[test_data]
git-tree-sha1 = "ce9bbe16fd5f390c0bde4ddc584460ed66a6d945"

    [[test_data.download]]
    sha256 = "acca15a40367de7f35cdedaaaf8462e0b41f9bb9d5391820fede962748896374"
    url = "https://github.com/ACEsuit/ACEhamiltonians_data/raw/update/test_data.tar.gz"
